import cookieParser from "cookie-parser";
import cors from "cors";
import express, { json, urlencoded } from "express";
export const app = express();
app.use(cookieParser());
app.use(cors({ origin: process.env.CORS_ORIGIN, credentials: true }));
app.use(urlencoded({ extended: true, limit: "15kb" }));
app.use(urlencoded({ extended: true }));
app.use(json());
app.use(errorHandler);
import userRouter from "./routes/user.routes.js";
import resumeRoutes from "./routes/resume.routes.js";
import resumeFeedbackRouter from "./routes/resumeFeedback.routes.js";
import { errorHandler } from "./middlewares/error.middleware.js";
app.use("/api/v1/users", userRouter);
app.use("/api/v1/resumes", resumeRoutes);
app.use("/api/v1/feedback", resumeFeedbackRouter);
